site_name: enum-extensions
site_author: nekitdev
site_description: Enhanced enumerations for Python.

repo_name: nekitdev/enum-extensions
repo_url: https://github.com/nekitdev/enum-extensions

remote_branch: github-pages

nav:
  - Index: "index.md"
  - Enums: "enums.md"
  - Flags: "flags.md"
  - Traits: "traits.md"

  - Reference:
    - Auto: "reference/auto.md"
    - Members: "reference/members.md"
    - Enums: "reference/enums.md"
    - Flags: "reference/flags.md"
    - Traits: "reference/traits.md"
    - Unique: "reference/unique.md"

  - Changelog: "changelog.md"
  - Security: "security.md"

watch:
  - docs
  - enum_extensions

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

      primary: deep purple
      accent: light blue

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default

      primary: deep orange
      accent: light blue

      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search

  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source

          paths: [enum_extensions]

          import:
            - https://docs.python.org/3/objects.inv

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
